import "abla/process/arguments"
import "game.ab"

fun main: int {
    val requested = if (processArgumentCount() > 0)
        processArgument(0)
    else "play"
    var mode = requested
    var backend = graphicsBackendAuto
    if (requested == "test-opengl") {
        mode = "test"
        backend = graphicsBackendOpenGl
    } else if (requested == "test-vulkan") {
        mode = "test"
        backend = graphicsBackendVulkan
    } else if (requested == "benchmark-opengl") {
        mode = "benchmark"
        backend = graphicsBackendOpenGl
    } else if (requested == "benchmark-vulkan") {
        mode = "benchmark"
        backend = graphicsBackendVulkan
    }
    doomRun(mode, backend)
}
